version: '3.9'

services:
  node1:
    build: .
    container_name: cli_node1
    networks:
      bitcoin_net:
        ipv4_address: 172.28.0.11
    stdin_open: true
    tty: true
    environment:
      - PORT=5000

  node2:
    build: .
    container_name: cli_node2
    networks:
      bitcoin_net:
        ipv4_address: 172.28.0.12
    stdin_open: true
    tty: true
    environment:
      - PORT=5000

  node3:
    build: .
    container_name: cli_node3
    networks:
      bitcoin_net:
        ipv4_address: 172.28.0.13
    stdin_open: true
    tty: true
    environment:
      - PORT=5000

  node4:
    build: .
    container_name: cli_node4
    networks:
      bitcoin_net:
        ipv4_address: 172.28.0.14
    stdin_open: true
    tty: true
    environment:
      - PORT=5000

  node5:
    build: .
    container_name: cli_node5
    networks:
      bitcoin_net:
        ipv4_address: 172.28.0.15
    stdin_open: true
    tty: true
    environment:
      - PORT=5000

  node6:
    build: .
    container_name: cli_node6
    networks:
      bitcoin_net:
        ipv4_address: 172.28.0.16
    stdin_open: true
    tty: true
    environment:
      - PORT=5000

networks:
  bitcoin_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
